name: chisel-sbom
summary: Chisel-SBOM is a software tool to generate SBOMs for chiselled file systems.
description: |
  Chisel-SBOM consumes the Chisel JsonWall-formatted manifest and generates a software
  bill of materials (SBOM) in SPDX JSON format.
source-code: https://github.com/rockcrafters/chisel-sbom
version: '0.0.1'
grade: devel
base: core24
confinement: strict

parts:
  chisel-sbom:
    plugin: go
    build-snaps: [go/latest/stable]
    source: .
    stage-packages:
      - git

apps:
  chisel-sbom:
    command: bin/chisel-sbom
    plugs: 
      - home
